service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls', namespace='system')),
    path('users/', include('users.urls', namespace='users')),
    path('contact/', include('contact.urls')),
]

system/urls.py
from django.urls import path

from system.apps import SystemConfig
from system.views import home, MailingCreateView, MailingUpdateView, MailingDeleteView, ClientCreateView, \
    MessageCreateView, MailingListView, disable_mailing, MailingLogList, MailingMessagesList, ClientListView

app_name = SystemConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('create/', MailingCreateView.as_view(), name='create'),
    path('update/<int:pk>', MailingUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', MailingDeleteView.as_view(), name='delete'),
    path('clients/create', ClientCreateView.as_view(), name='create_client'),
    path('message/create', MessageCreateView.as_view(), name='create_message'),
    path('mailings/', MailingListView.as_view(), name='mailings'),
    path('mailings/disable/<int:pk>', disable_mailing, name='disable'),
    path('log/', MailingLogList.as_view(), name='log'),
    path('messages/', MailingMessagesList.as_view(), name='messages'),
    path('clients/', ClientListView.as_view(), name='clients')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, UserRegisterView, UserUpdateView, activate_new_user, UsersListView, \
    block_user

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('activate/<int:pk>/', activate_new_user, name='activate'),
    path('users_list/', UsersListView.as_view(), name='users_list'),
    path('block_user/<int:pk>', block_user, name='block_user')
]

system/models.py
from django.conf import settings
from django.db import models
from users.models import User

# варианты периодичности рассылки (раз в день, в неделю, в месяц)
MAILING_PERIODICITY = [(1, 'раз в день'), (2, 'раз в неделю'), (3, 'раз в месяц')]

# варианты статуса рассылки
MAILING_STATUS = [(1, 'завершена'), (2, 'создана'), (3, 'запущена')]

# необязательное поле
NULLABLE = {'blank': True, 'null': True}


class System(models.Model):
    name = models.CharField(max_length=350, unique=True, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f'{self.name} ({self.description})'

    class Meta:
        verbose_name = 'система'
        verbose_name_plural = 'системы'


class MailingMessage(models.Model):
    """Сообщение для рассылки"""

    title = models.CharField(max_length=150, verbose_name='Тема сообщения')
    message = models.TextField(verbose_name='Тело сообщения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.title


class Mailing(models.Model):
    """Настройка для рассылки"""

    date_time = models.DateTimeField(verbose_name='время рассылки')
    periodicity = models.PositiveSmallIntegerField(choices=MAILING_PERIODICITY, default=1, verbose_name='периодичность')
    status = models.PositiveSmallIntegerField(choices=MAILING_STATUS, default=2, verbose_name='статус рассылки')
    client = models.ManyToManyField(User, related_name='client_mailings', verbose_name='клиент рассылки')
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE, verbose_name='сообщение для рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='owner_mailings', on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return f'Рассылка на {self.date_time} с периодичностью {self.periodicity}. Статус {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [('can_view_mailings', 'can_view_mailings'),
                       ('can_disable_mailings', 'can_disable_mailings'),
                       ]


class MailingLog(models.Model):
    """Логи рассылки"""

    date_time = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    status = models.CharField(max_length=100, verbose_name='Статус попытки')
    answer = models.CharField(max_length=100, verbose_name='Ответ сервера', **NULLABLE)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'


class Blog(models.Model):
    """Блог"""

    title = models.CharField(max_length=100, verbose_name='заголовок')
    description = models.TextField(verbose_name='содержимое статьи')
    image = models.ImageField(upload_to='image/', verbose_name='изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')
    published_at = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')

    def __str__(self):
        return f'{self.title} ({self.description})'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блог'

system/forms.py
from django import forms

from system.models import Mailing


class MailingForm(forms.ModelForm):
    """Форма для создания рассылки"""

    class Meta:
        model = Mailing

        fields = ('date_time', 'periodicity', 'client', 'message')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

system/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from system.cron import send_email_tasks
from system.forms import MailingForm
from system.models import Mailing, User, MailingMessage, Blog, MailingLog


@cache_page(60)
def home(request):
    """Домашняя страница"""
    posts = Blog.objects.all()
    posts_for_context = []
    if len(posts) > 3:
        for i in range(3):
            number = random.randint(0, len(posts))
            posts_for_context.append(posts[number])
            print(posts[number])
    else:
        posts_for_context = posts

    if request.user.has_perm('service.can_disable_mailings'):
        mailing_list = Mailing.objects.filter(status=2 or 3)
        mailing_all = Mailing.objects.all()

    else:
        mailing_list = Mailing.objects.filter(status=2 or 3,
                                              owner=request.user.pk)
        mailing_all = Mailing.objects.filter(owner=request.user.pk)

    count_clients = User.objects.all()
    context = {'object_list': mailing_list, 'title': 'Список активных рассылок',
               'count_active_mailings': len(mailing_list),
               'count_mailings': len(mailing_all),
               'posts': posts_for_context,
               'count_clients': len(count_clients)}
    return render(request, 'system/index.html', context)


class MailingListView(ListView):
    """Все имеющиеся рассылки"""
    model = Mailing
    template_name = 'system/mailings_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Список всех рассылок'
        return context

    def get_queryset(self):
        if self.request.user.has_perm('service.can_disable_mailings'):
            return super().get_queryset()

        else:
            return Mailing.objects.filter(owner=self.request.user.pk)


class MailingCreateView(CreateView, LoginRequiredMixin):
    """Создание рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('system:index')

    def form_valid(self, form):
        mailing = form.save()
        mailing.owner = self.request.user
        send_email_tasks()
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(UpdateView, LoginRequiredMixin):
    """Редактирования рассылок"""

    model = Mailing
    fields = ('date_time', 'periodicity', 'client', 'status', 'message')
    success_url = reverse_lazy('system:index')


class MailingDeleteView(DeleteView, LoginRequiredMixin):
    """Удаления рассылки"""

    model = Mailing
    success_url = reverse_lazy('system:index')


class ClientCreateView(CreateView, LoginRequiredMixin):
    """Создание клиента"""

    model = User
    success_url = reverse_lazy('system:create')
    fields = ('email', 'first_name', 'last_name', 'comment')


class MessageCreateView(CreateView, LoginRequiredMixin):
    """Создание сообщения"""

    model = MailingMessage
    fields = ('title', 'message')
    success_url = reverse_lazy('system:create')


def disable_mailing(pk):
    """Отключение рассылок"""

    mailing_for_disable = Mailing.objects.get(pk=pk)
    mailing_for_disable.status = 1
    mailing_for_disable.save()
    return redirect(reverse('system:mailings'))


class MailingLogList(ListView, LoginRequiredMixin):
    model = MailingLog

    def get_queryset(self):
        return MailingLog.objects.filter(mailing__owner=self.request.user)


class MailingMessagesList(ListView, LoginRequiredMixin):
    model = MailingMessage

    def get_queryset(self):
        if self.request.user.is_superuser:
            return super().get_queryset()

        return MailingMessage.objects.filter(owner=self.request.user)


class ClientListView(ListView, LoginRequiredMixin):
    model = User

    def get_queryset(self):
        if self.request.user.is_superuser:
            return super().get_queryset()
        return User.objects.filter(owner=self.request.user)

system/templates/system/base.html
{% load contact_tags %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
    }

    .bi {
        vertical-align: -.125em;
        fill: currentColor;
    }

    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
    }

    .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
        z-index: 1500;
    }
</style>

<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24"></svg>
            </a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'system:create' %}">Создать
                рассылку</a>
            <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4></h4>
                    <p class="text-body-secondary"></p>
                </div>
                <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
                    <nav class="ms-6">
                        <div class="col-sm-4 offset-md-1 py-4">
                            <h4>Меню</h4>
                            <ul class="list-unstyled">
                                <li><a href="{% url 'system:mailings' %}" class="text-white">Все рассылки</a></li>
                                <li><a href="{% url 'users:users_list' %}" class="text-white">Пользователи</a></li>
                                <li><a href="{% url 'system:messages' %}" class="text-white">Сообщения</a></li>
                                {% if user.is_authenticated %}
                                    <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                                    <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                                {% else %}
                                    <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="bg-dark text-secondary px-4 py-5 text-center">
    <div class="py-5">
        <h1 class="display-5 fw-bold text-white">Сервис рассылок</h1>
        <div class="col-lg-6 mx-auto">
            <p class="fs-5 mb-4">Зарегистрируйся и пользуйся.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                {% if user.is_authenticated %}
                    <button><a class="p-2 btn btn-outline-primary btn-dark text-white" href="{% url 'users:logout' %}">
                        Выйти
                    </a></button>
                {% else %}
                    <button><a class="p-2 btn btn-outline-primary btn-dark text-white" href="{% url 'users:login' %}">
                        Войти
                    </a>
                        <a class="p-2 btn btn-outline-primary btn-dark text-white" href="{% url 'users:register' %}">
                            Регистрация
                        </a></button>
                {% endif %}

            </div>
        </div>
    </div>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>
<div class="b-example-divider mb-0"></div>
<div class="col-lg-8 footer-right">
    <div class="w3layouts-news-letter">
        {% contact_form %}
    </div>
</div>

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">{{ title }}</h1>
        </div>
    </div>
</section>

</main>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">

            <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
        </div>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/color_modes.js' %}"></script>

</body>
<body>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

system/templates/system/index.html
{% extends 'system/base.html'%}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">{{ title }}</p>
    </div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.date_time }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Клиенты:</h6>
                        <li>{{ object.client.all | join:", " }}</li>
                        <h6>Сообщение:</h6>
                        <li>{{ object.message }}</li>
                        <h6>Периодичность:</h6>
                         <li>{{ object.get_periodicity_display }}</li>
                        <h6>Статус:</h6>
                        <li>{{ object.get_status_display }}</li>
                    </ul>
                    {% if object.owner == user or user.is_superuser %}
                        <a href="{% url 'system:update' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                        <a href="{% url 'system:delete' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
                    {% elif perms.service.can_disable_mailings %}
                        <a href="{% url 'system:disable' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Отключить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="container">
    <div class="row text-center">
        {% for post in posts %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ post.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Описание:</h6>
                        <li>{{ post.description }}</li>
                        <h6>Изображение:</h6>
                         <li>{{ post.image }}</li>
                        <h6>Количество просмотров:</h6>
                        <li>{{ post.views_count }}</li>
                        <h6>Дата создания:</h6>
                        <li>{{ post.published_at }}</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Статистика сервиса</p>
    <h6>Количество активных рассылок:</h6>
        <li>{{ count_active_mailings }}</li>
    <h6>Общее количество рассылок:</h6>
        <li>{{ count_mailings }}</li>
    <h6>Количество уникальных клиентов для рассылок</h6>
        <li>{{ count_clients }}</li>
</div>

{% endblock %}

system/templates/system/mailing_form.html
{% extends 'system/base.html'%}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Создание рассылки
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-success">Сохранить</button>
            </div>
        </div>
    </div>
<nav class="ms-6">
<a href="{% url 'system:create_client' %}" type="button" class="p-1 btn btn-outline-primary">Добавить клиента</a>
<a href="{% url 'system:create_message' %}" type="button" class="p-1 btn btn-outline-primary">Добавить сообщение</a>
</nav>
</form>

{% endblock %}

system/templates/system/mailings_list.html
{% extends 'system/base.html'%}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <p class="lead">{{ title }}</p>
    </div>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.date_time }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h6>Клиенты:</h6>
                        <li>{{ object.client.all | join:", " }}</li>
                        <h6>Сообщение:</h6>
                        <li>{{ object.message }}</li>
                        <h6>Периодичность:</h6>
                         <li>{{ object.get_periodicity_display }}</li>
                        <h6>Статус:</h6>
                        <li>{{ object.get_status_display }}</li>
                    </ul>
                    {% if object.owner == user or user.is_superuser %}
                        <a href="{% url 'system:update' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                        <a href="{% url 'system:delete' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
                    {% elif perms.service.can_disable_mailings %}
                        <a href="{% url 'system:disable' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Отключить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}